### ISSUE TITLE
DF Manual Rolls: Stopped working with PF2

### ISSUE THREAD

**Issue by Shepardkx** [flamewave000/dragonflagon-fvtt#106]
**Module**
Manual Rolls 1.2.1

**Describe the issue**
I have tried running manual rolls again and it's not working with the PF@ system. I tried disabling every modules but Manual roll to make sure it wasn't an interference with another mod. It looks like the mod is not activating even if I check it on. I get not message in the console either.

**Comment by peaceful-octopus** [comment]
The module doesn't work in PF1e either. It just doesn't show up in the configs at all. It does appear to still work in 5e worlds.

**Comment by Shepardkx** [comment]
I just updated and tried in my test world with only manual roll and libwrapper and it's not working on pf 2.

W: Error detected in module 'df-manual-rolls'.
A wrapper for 'Roll.prototype._evaluate' has already been registered by module 'df-manual-rolls'.
    at Function.🎁register [as register] (http://10.0.0.15:30000/modules/lib-wrapper/lib-wrapper.js:1:29757)
    at Function.patch (http://10.0.0.15:30000/modules/df-manual-rolls/src/df-manual-rolls.js:5:887)
    at Object.onChange (http://10.0.0.15:30000/modules/df-manual-rolls/src/df-manual-rolls.js:7:1320)
    at ClientSettings.set (http://10.0.0.15:30000/scripts/foundry.js:1210:61)
    at SettingsConfig._updateObject (http://10.0.0.15:30000/scripts/foundry.js:31094:29)
    at SettingsConfig._onSubmit (http://10.0.0.15:30000/scripts/foundry.js:2816:18)
_onSubmit @ foundry.js:2819

When I check the box to use manual rolls in the setting.

**Comment by flamewave000** [comment]
This appears to be completely unrelated to PF2. It's a bug you've discovered. I won't reopen this ticket as I'm already redoing the settings for the module to provide some better control 👍🏽

**Comment by Shepardkx** [comment]
Do you want me to open a new issue for it or no need?

**Comment by flamewave000** [comment]
I'll have to pull the PF2 system and take a look. My guess is that PF2 has not yet upgraded their character sheets to use the new async roll system. You may have to wait for that, maybe open a ticket with the system's repo for it.

**Comment by Shepardkx** [comment]
I've asked the System devs on PF2e discord and they say all the sheets are upgraded to the new async roll system.

**Comment by flamewave000** [comment]
I've also spoken to Nikolaj, who built the PF2 system. Everything has been "upgraded" but not everything is using the new Async Rolls. Particularly the deprecated `DicePF2e` helper that still uses legacy rolls. It's not anything I can fix and you will unfortunately have to wait until him or another community dev can push an update to remove the old `DicePF2e` helper.
