### ISSUE TITLE
Curvy Walls:  npx gulp failing on Windows.

### ISSUE THREAD

**Issue by leemahn** [flamewave000/dragonflagon-fvtt#378]
**Module**
DF Curvy Walls v3.3.1

**Describe the issue**
I am on a Windows 11 machine - latest npm installed.  "npx gulp" command generates an error.

**To Reproduce**
- Cloned latest repo
- Changed to df-curvy-walls directory
- Ran "nvm install" (several warnings of deprecated commands - but no errors)
- Ran "npx gulp" and received the following error:

C:\exports\dragonflagon-fvtt\df-curvy-walls>npx gulp
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
[14:39:11] Working directory changed to C:\exports\dragonflagon-fvtt
Error: ENOENT: no such file or directory, open 'module.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (C:\exports\dragonflagon-fvtt\gulpfile.js:31:29)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImport (C:\exports\dragonflagon-fvtt\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'module.json'
}

It is correct, there is no such file in that directory.

**Expected behavior**
Proper installation build of compiled module into the "/dist" directory (not created)

**Comment by flamewave000** [comment]
Are you trying to build this module yourself to play around? Or are you trying to install this in Foundry?

If you are trying to build the project, I have a highly tailored build system I've put together with various scripts. This cannot be built on anything but a Linux based system. So either WSL for Windows (which I use), a Linux distro like Ubuntu, or MacOS.

To do this, you will need to follow the instructions found here : [For Developers](https://github.com/flamewave000/dragonflagon-fvtt#for-developers)

**Comment by leemahn** [comment]
Yes.. I was trying to build it myself.  However, I found out - shortly after posting my report - that you have a module in Foundry already.  I followed a link provided by someone on Foundry to get me to your GitHub repository.  That's why I was trying.  All good - I have it installed now and it's working perfectly. 

Thanks.

**Comment by flamewave000** [comment]
Yeah all of my modules in GitHub are officially registered and released in the Foundry module market 👍🏽
