### ISSUE TITLE
WhisperTruncation._messageRender - Error in the console (F12)

### ISSUE THREAD

**Issue by CaosFR** [flamewave000/dragonflagon-fvtt#389]
**Module**
DragonFlagon Chat Enhancements v4.0.0

**Describe the issue**
First at all, thanks for your wonderfull work and modules.
When I launch my game I have a error in the console (F12). Of course I have try to disable all my modules execpt this one and it's dependency. For information my game system is in french.

**To Reproduce**
1. Launch a Game
2. Click on F12
3. See a error on 1 package of df-chat-enhance.

**Expected behavior**
Nothing, it's just a report for solve this error.

**Screenshots (Optional)**
```
Error: Cannot read properties of undefined (reading 'data')
[Detected 1 package: df-chat-enhance]
    at WhisperTruncation._messageRender (whisper-trunc.ts:48:24)
    at Hooks._call (foundry.js:294:14)
    at Hooks.call (foundry.js:279:33)
    at ChatMessage.getHTML (foundry.js:15308:11)
    at async 🎁ChatMessage.prototype.getHTML#df-chat-enhance (PlayerColor.ts:59:10)
    at async ChatLog._renderBatch (foundry.js:57754:21)
    at async ChatLog._renderInner (foundry.js:57723:5)
    at async ChatLog._render (foundry.js:3068:19)
    at async ChatLog._render (foundry.js:47136:5)
    at async ChatLog._render (foundry.js:57714:5)
  | onError | @ | foundry.js:319
-- | -- | -- | --
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:511
  | 🎁Hooks.onError#lib-wrapper | @ | listeners.js:137
  | 🎁Hooks.onError#0 | @ | libWrapper-wrapper.js:187
  | _call | @ | foundry.js:298
  | call | @ | foundry.js:279
  | getHTML | @ | foundry.js:15308
  | await in getHTML (async) |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:511
  | 🎁ChatMessage.prototype.getHTML#df-chat-enhance | @ | PlayerColor.ts:59
  | 🎁call_wrapper | @ | libWrapper-wrapper.js:620
  | 🎁ChatMessage.prototype.getHTML#0 | @ | libWrapper-wrapper.js:189
  | _renderBatch | @ | foundry.js:57754
  | await in _renderBatch (async) |   |  
  | _renderInner | @ | foundry.js:57723
  | await in _renderInner (async) |   |  
  | _render | @ | foundry.js:3068
  | await in _render (async) |   |  
  | _render | @ | foundry.js:47136
  | _render | @ | foundry.js:57714
  | _render | @ | foundry.js:46924
  | await in _render (async) |   |  
  | render | @ | foundry.js:3021
  | initializeUI | @ | foundry.js:5651
  | setupGame | @ | foundry.js:5544
  | await in setupGame (async) |   |  
  | _initializeGameView | @ | foundry.js:6514
  | _initializeView | @ | foundry.js:6490
  | initialize | @ | foundry.js:5431
  | await in initialize (async) |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:511
  | 🎁libWrapperInit | @ | libWrapper-api.js:796
  | await in 🎁libWrapperInit (async) |   |  
  | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:187
  | window.addEventListener.once | @ | foundry.js:62701
```
Thanks for your help.

**Comment by flamewave000** [comment]
This should be fixed in v5.0.0 which supports FoundryVTT v12
