### ISSUE TITLE
DF Chat Enhancements: Failed to open chat archive

### ISSUE THREAD

**Issue by GCSmith-07** [flamewave000/dragonflagon-fvtt#421]
**Module**
DF Chat Enhancements 4.1.0

**Describe the issue**
Archived chat logs will show up when you go to the archive manager but it fails to open them. I will attach the console output:

Failed to load resource: the server responded with a status of 404 ()
Failed to read JSON for archive worlds/adventures-of-darkstone-island/chat-archive/1_Sat%20June%2011%202022%20-%20Sat%20Nov%2012%202022.json
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
(anonymous) @ DFChatArchive.ts:170
Error: Could not access the archive from server side: worlds/adventures-of-darkstone-island/chat-archive/1_Sat%20June%2011%202022%20-%20Sat%20Nov%2012%202022.json
[Detected 1 package: df-chat-enhance]
    at DFChatArchive.getArchiveContents (DFChatArchive.ts:174:10)
    at async DFChatArchiveViewer.ts:157:10
    at async DFChatArchiveViewer._render (foundry.js:5073:19)
onError @ foundry.js:747

It should bring up the archived chat log in a window (within foundry) according to the module description.

**Comment by darloth** [comment]
Looks like a duplicate of #416 , and it looks like you've discovered the same problem - namely that if you save an archive with spaces in the name it won't load properly.

As a workaround, you can save archives with dashes (-) instead of spaces and that seems to work, but renaming old archives doesn't help, they still were broken.

**Comment by GCSmith-07** [comment]
> Looks like a duplicate of #416 , and it looks like you've discovered the same problem - namely that if you save an archive with spaces in the name it won't load properly.
> 
> As a workaround, you can save archives with dashes (-) instead of spaces and that seems to work, but renaming old archives doesn't help, they still were broken.

Do you think if I made a new archive and then copied the data from an old archive I would be able to see the log again?

**Comment by chaoticnote** [comment]
Foundry Version 10, build 291
module version 4.1.0

This problem still exists. Can confirm that any chat archive with spaces are not openable, but using dashes in place of them will work. Feels unintuitive though and I hope this gets fixed soon.

**Comment by flamewave000** [comment]
This is fixed in v5.0.0 which supports FoundryVTT v12
