### ISSUE TITLE
DF Chat Enhancements: Errors on opening User Configuration in PF2e

### ISSUE THREAD

**Issue by esheyw** [flamewave000/dragonflagon-fvtt#452]
**Module**
DF CE 4.1.0, PF2e 4.7.4, Foundry 10.291

**Describe the issue**
every time a user configuration window is opened from the playerlist context menu, an error is thrown:
```
foundry.js:747 TypeError: Error thrown in hooked function '' for hook 'renderUserConfig'. Cannot read properties of undefined (reading '0')
[Detected 1 package: df-chat-enhance]
    at df-adventure-log.ts:88:24
    at Array.map (<anonymous>)
    at Object.fn (df-adventure-log.ts:85:76)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at UserConfigPF2e._render (foundry.js:5153:13)
    at async UserConfigPF2e._render (foundry.js:5822:5)
 ```
 no other modules active besides MM+, DsN, and find the culprit

**Comment by flamewave000** [comment]
This seems to be fixed in v5.0.0 which supports FoundryVTT v12
