### ISSUE TITLE
DF Chat Enchantments: Error in console when try log as quote

### ISSUE THREAD

**Issue by Ryach** [flamewave000/dragonflagon-fvtt#463]
Error in console when trying log as quote the button log as Event work without problems 

```
DFAdventureLogProcessor.ts:156 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'name')
[Detected 1 package: df-chat-enhance]
    at Object. callback (DFAdventureLogProcessor.ts:156:77)
    at #onClickItem (foundry.js:55711:11)
    at HTMLElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

**Comment by flamewave000** [comment]
This is fixed in v5.0.0 which supports FoundryVTT v12
