### ISSUE TITLE
DF Scene Enchancement: v11 broken

### ISSUE THREAD

**Issue by PwQt** [flamewave000/dragonflagon-fvtt#478]
**Module**
DF Scene Enhancement 3.6.0
Foundry v11.300
DND5e 2.2.1

**Describe the issue**
A exception occurs + an error message appears after loading the module to check the console.

**Console exception message**

> foundry.js:753 LibWrapperPackageError: lib-wrapper. Error detected in module DF Scene Enhancement. It is likely this module has not been updated for FVTT Version 11 Stable.
This is *not* a libWrapper bug.
Find information about this module here: https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-scene-enhance
Report this issue here: https://github.com/flamewave000/dragonflagon-fvtt/issues

> == Technical Details:
Detected by libWrapper.
Package ID= df-scene-enhance
Error= Can't wrap 'SceneDirectory.prototype._onClickDocumentName', target does not exist or could not be found.

> [Detected 2 packages: lib-wrapper, df-scene-enhance]
    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at de (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at DFSceneNav.patchSceneDirectoryClick (df-scene-nav.ts:21:15)
    at DFSceneNav.ready (df-scene-nav.ts:124:14)
    at Object.fn (df-scene-enhance.ts:20:2)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.setupGame (foundry.js:8684:11)
    at async Game._initializeGameView (foundry.js:9925:5)
    at async Game.initialize (foundry.js:8588:5)

**To Reproduce**
1. Update to 11.300
2. Launch any game

**Screenshots (Optional)**
![obraz](https://github.com/flamewave000/dragonflagon-fvtt/assets/12457218/0bbe6169-c0a5-499a-bf6b-fe011bc68e53)

In addition if possible the module posts as a `compatibility risk` in server module management:
![obraz](https://github.com/flamewave000/dragonflagon-fvtt/assets/12457218/e3589592-6b85-4869-a947-5bec7a8cd24d)

**Comment by PwQt** [comment]
any plans on updating it?

**Comment by davelacorneille** [comment]
+1

**Comment by Gray-Geist** [comment]
+1

**Comment by PwQt** [comment]
From taking a small sneak peek into the API, it seems like the issue is with removal of the 
```
SidebarDirectory._onClickDocumentName();
``` 
method. The `SceneDirectory` class now inherits over `DocumentDirectory` class.

**Comment by Nemodious** [comment]
+1, I have other modules dependent on this module (pretty sure anyway?) and this has been an issue for a while now. Thank you!

**Comment by Nemodious** [comment]
foundry.js:68095 DF Scene Enhancement: Error detected in module. It is likely this module has not been updated for FVTT Version 11 Stable. (See JS Console)
fetch @ foundry.js:68095
foundry.js:753 LibWrapperPackageError: lib-wrapper. Error detected in module DF Scene Enhancement. It is likely this module has not been updated for FVTT Version 11 Stable.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-scene-enhance
Report this issue here: https://github.com/flamewave000/dragonflagon-fvtt/issues

== Technical Details:
Detected by libWrapper.
Package ID= df-scene-enhance
Error= Can't wrap 'SceneDirectory.prototype._onClickDocumentName', target does not exist or could not be found.

[Detected 2 packages: lib-wrapper, df-scene-enhance]
    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at de (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at DFSceneNav.patchSceneDirectoryClick (df-scene-nav.ts:21:15)
    at DFSceneNav.ready (df-scene-nav.ts:124:14)
    at Object.fn (df-scene-enhance.ts:20:2)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.setupGame (foundry.js:8666:11)
    at async Game._initializeGameView (foundry.js:9908:5)
    at async Game.initialize (foundry.js:8570:5)

**Comment by yjeroen** [comment]
Still hoping this gets resolved. :)

**Comment by Woazboat** [comment]
Simply changing `SceneDirectory.prototype._onClickDocumentName` to  `SceneDirectory.prototype._onClickEntryName` [here](https://github.com/flamewave000/dragonflagon-fvtt/blob/master/df-scene-enhance/src/df-scene-nav.ts#L21-L29) fixed the issue and made the module work again for me.

**Comment by flamewave000** [comment]
Fixed in 4.0.0 for FoundryVTT v12+
