### ISSUE TITLE
DF Module Name: Conflicting module names...

### ISSUE THREAD

**Issue by Motara7** [flamewave000/dragonflagon-fvtt#492]
**Conflicting Module(s)**
- libWrapper + JB2A (Automated Animations)

**Describe the conflict**
When I have DF Chat Enhancements (requires libWrapper) running with JB2A (requires: Automated Animations, Sequencer, and socketlib), Automatic Animations doesn't animate anything and throws the following error:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'metadata')
    at Object.fn (aa-pf1.js:19:35)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13526:13)
    at foundry.js:13498:43
    at Array.map (<anonymous>)
    at #handleCreateDocuments (foundry.js:13498:33)

Everything works fine when I run my game without DF Chat Enhancements.

**Expected behavior**
I expected Automatic Animations to work as normal.

**Screenshots (Optional)**
N/A

**Additional context (Optional)**
Foundry VTT v11 Build 308
Pathfinder 1 9.4
Automated Animations 4.2.66
DF Chat Enhancements 4.1.0
libWrapper 1.12.13.0
Sequencer 3.1.4
socketlib 1.0.13

**Comment by flamewave000** [comment]
v11 was not supported. This does not appear to be an issue in the latest release for v12.
